name: Build Baritone
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Required parameter
          java-version: '17'
      - name: Build with Gradle
        run: ./gradlew build
      - uses: actions/upload-artifact@v3
        with:
          name: baritone.jar
          path: build/libs/*.jar
